### ISSUE TITLE
Local wheel built on Mac OS seg faults when loading wrapper library

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/epanet-python#78] opened 2021-07-06 16:44 UTC
Building owa-epanet wheel locally on Mac OS 11.4 with Python 3.8 running in a Conda env. 

The build and install proceed as normal. I get the following error when running pytest

```
(py38) michaeltryby@iMac-Pro owa-epanet % pytest 
======================================== test session starts =========================================
platform darwin -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/michaeltryby/Workspace/OWA/epanet-python/owa-epanet
collecting ... Fatal Python error: Segmentation fault

Current thread 0x0000000109d6ce00 (most recent call first):
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1166 in create_module
  File "<frozen importlib._bootstrap>", line 556 in module_from_spec
  File "<frozen importlib._bootstrap>", line 657 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1042 in _handle_fromlist
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/epanet/toolkit.py", line 13 in <module>
  ...
```

**Comment by samhatchett** [comment] 2021-07-06 21:12
dupe of #82

**Closed as completed by samhatchett** 2021-07-06 21:12 UTC
