### ISSUE TITLE
Errors on installation of epanet-python package

### ISSUE THREAD

**Issue by LittleZi** [OpenWaterAnalytics/epanet-python#72] opened 2021-06-15 06:06 UTC
After installing owa-epanet on my computer using the code `pip install owa-epanet,`  I just ran the code `python3 setup.py sdist bdist_wheel`, but it returned the error shown below:
```
`C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\Lib\site-packages\owa-epanet>python setup.py sdist bdist_wheel


--------------------------------------------------------------------------------
-- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator
--------------------------------
---------------------------
----------------------
-----------------
------------
-------
--
Not searching for unused variables given on the command line.
-- The C compiler identification is MSVC 19.16.27045.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is MSVC 19.16.27045.0
CMake Warning (dev) at C:/Users/Ziyuan/AppData/Local/Programs/Python/Python37/Lib/site-packages/cmake/data/share/cmake-3.18/Modules/CMakeDetermineCXXCompiler.cmake:157 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  CMakeLists.txt:4 (ENABLE_LANGUAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Users/Ziyuan/AppData/Local/Programs/Python/Python37/Lib/site-packages/cmake/data/share/cmake-3.18/Modules/CMakeDetermineCXXCompiler.cmake:177 (elseif):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  CMakeLists.txt:4 (ENABLE_LANGUAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Ziyuan/AppData/Local/Programs/Python/Python37/Lib/site-packages/owa-epanet/_cmake_test_compile/build
--
-------
------------
-----------------
----------------------
---------------------------
--------------------------------
-- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator - success
--------------------------------------------------------------------------------

Configuring Project
  Working directory:
    C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\Lib\site-packages\owa-epanet\_skbuild\win-amd64-3.7\cmake-build
  Command:
    cmake 'C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\Lib\site-packages\owa-epanet' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\Lib\site-packages\owa-epanet\_skbuild\win-amd64-3.7\cmake-install' '-DPYTHON_EXECUTABLE:FILEPATH=C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\python.exe' -DPYTHON_VERSION_STRING:STRING=3.7.9 '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\Include' '-DPYTHON_LIBRARY:FILEPATH=C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\libs\python37.lib' -DSKBUILD:BOOL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\lib\site-packages\skbuild\resources\cmake' -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release

-- The project is built using scikit-build
PYTHONLIBS_VERSION_STRING: 3.7.9
CMAKE_SWIG_FLAGS: -py3
CMake Error at CMakeLists.txt:38 (ADD_SUBDIRECTORY):
  The source directory

    C:/Users/Ziyuan/AppData/Local/Programs/Python/Python37/Lib/site-packages/owa-epanet/EPANET

  does not contain a CMakeLists.txt file.


CMake Warning (dev) at C:/Users/Ziyuan/AppData/Local/Programs/Python/Python37/Lib/site-packages/cmake/data/share/cmake-3.18/Modules/UseSWIG.cmake:634 (message):
  Policy CMP0078 is not set: UseSWIG generates standard target names.  Run
  "cmake --help-policy CMP0078" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

Call Stack (most recent call first):
  CMakeLists.txt:42 (SWIG_ADD_LIBRARY)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Users/Ziyuan/AppData/Local/Programs/Python/Python37/Lib/site-packages/cmake/data/share/cmake-3.18/Modules/UseSWIG.cmake:486 (message):
  Policy CMP0086 is not set: UseSWIG honors SWIG_MODULE_NAME via -module
  flag.  Run "cmake --help-policy CMP0086" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  C:/Users/Ziyuan/AppData/Local/Programs/Python/Python37/Lib/site-packages/cmake/data/share/cmake-3.18/Modules/UseSWIG.cmake:736 (SWIG_ADD_SOURCE_TO_MODULE)
  CMakeLists.txt:42 (SWIG_ADD_LIBRARY)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:44 (set_property):
  set_property could not find TARGET epanet2.  Perhaps it has not yet been
  created.


-- Configuring incomplete, errors occurred!
See also "C:/Users/Ziyuan/AppData/Local/Programs/Python/Python37/Lib/site-packages/owa-epanet/_skbuild/win-amd64-3.7/cmake-build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\lib\site-packages\skbuild\setuptools_wrap.py", line 586, in setup
    languages=cmake_languages
  File "C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\lib\site-packages\skbuild\cmaker.py", line 240, in configure
    os.path.abspath(CMAKE_BUILD_DIR())))

An error occurred while configuring with CMake.
  Command:
    cmake 'C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\Lib\site-packages\owa-epanet' -G Ninja '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\Lib\site-packages\owa-epanet\_skbuild\win-amd64-3.7\cmake-install' '-DPYTHON_EXECUTABLE:FILEPATH=C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\python.exe' -DPYTHON_VERSION_STRING:STRING=3.7.9 '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\Include' '-DPYTHON_LIBRARY:FILEPATH=C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\libs\python37.lib' -DSKBUILD:BOOL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\lib\site-packages\skbuild\resources\cmake' -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=10.9 -DCMAKE_BUILD_TYPE:STRING=Release
  Source directory:
    C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\Lib\site-packages\owa-epanet
  Working directory:
    C:\Users\Ziyuan\AppData\Local\Programs\Python\Python37\Lib\site-packages\owa-epanet\_skbuild\win-amd64-3.7\cmake-build
Please see CMake's output for more information`
```
Could you please give me some ideas about how to fix this issue? Thanks a lot in advance!

**Comment by samhatchett** [comment] 2021-06-15 15:01
duplicate of #71

**Closed as completed by samhatchett** 2021-06-15 15:01 UTC
