### ISSUE TITLE
Library import error when running owa-epanet MacOS wheel installed from pypi

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/epanet-python#79] opened 2021-07-06 16:49 UTC
Running Python 3.8 in a Conda env on Mac OS 11.4. 

When I run owa-epanet wheel binary install from pypi I get the following library import error
 
```
(py38) michaeltryby@iMac-Pro owa-epanet % pytest
======================================== test session starts =========================================
platform darwin -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/michaeltryby/Workspace/OWA/epanet-python/owa-epanet
collected 0 items / 1 error                                                                          

=============================================== ERRORS ===============================================
______________________________ ERROR collecting test/test_owa_epanet.py ______________________________
ImportError while importing test module '/Users/michaeltryby/Workspace/OWA/epanet-python/owa-epanet/test/test_owa_epanet.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/anaconda3/envs/py38/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_owa_epanet.py:5: in <module>
    import epanet.toolkit as en
/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/epanet/toolkit.py:13: in <module>
    from . import _toolkit
E   ImportError: dlopen(/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/epanet/_toolkit.so, 2): Library not loaded: /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/Python
E     Referenced from: /usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/epanet/_toolkit.so
E     Reason: image not found
====================================== short test summary info =======================================
ERROR test/test_owa_epanet.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================== 1 error in 0.16s ==========================================
```

**Comment by samhatchett** [comment] 2021-07-06 21:11
dupe of #82

**Closed as completed by samhatchett** 2021-07-06 21:11 UTC
