### ISSUE TITLE
Local wheel built on Windows many unit tests are failing

### ISSUE THREAD

**Issue by michaeltryby** [OpenWaterAnalytics/epanet-python#81] opened 2021-07-06 19:41 UTC
Building owa-epanet wheel locally on Windows 10 with Python 3.7 running in Conda env. 

The build and install proceed as normal. 21 of 24 unit tests fail when running pytest. Typical error follows

```
FAILED test/test_owa_epanet.py::test_open - PermissionError: [WinError 32] The process cannot access the file because...
```

**Comment by samhatchett** [comment] 2021-07-06 21:11
dupe of #82

**Closed as completed by samhatchett** 2021-07-06 21:11 UTC
